using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Charlotte.GameCommons;

namespace Charlotte
{
	public static class Musics
	{
		public static Music DancingFuries = new Music(@"Music\ajapa\Dancing Furies.mp3");
		public static Music DesireDrive = new Music(@"Music\ajapa\Desire Drive.mp3");
		public static Music EndOfTheEnd = new Music(@"Music\ajapa\End of The End.mp3");
		public static Music FlanInTheSpace = new Music(@"Music\ajapa\Flan In The Space.mp3");
		public static Music TheDisputeWorld = new Music(@"Music\ajapa\The Dispute World.mp3");
		public static Music TheLabyrinth = new Music(@"Music\ajapa\The Labyrinth.mp3");
		public static Music UnfortunateParade = new Music(@"Music\ajapa\Unfortunate Parade.mp3");
		public static Music あいまいな東方裁判 = new Music(@"Music\ajapa\あいまいな東方裁判.mp3");
		public static Music アンリアル = new Music(@"Music\ajapa\アンリアル.mp3");
		public static Music ヴェネツィアワルツ = new Music(@"Music\ajapa\ヴェネツィアワルツ.mp3");
		public static Music うたた寝 = new Music(@"Music\ajapa\うたた寝.mp3");
		public static Music エイリアンの休日 = new Music(@"Music\ajapa\エイリアンの休日.mp3");
		public static Music オーエンとの戦い = new Music(@"Music\ajapa\オーエンとの戦い.mp3");
		public static Music おてんば恋娘オルゴールver = new Music(@"Music\ajapa\おてんば恋娘オルゴールver.mp3");
		public static Music こいしの大冒険 = new Music(@"Music\ajapa\こいしの大冒険.mp3");
		public static Music さとりんステップ = new Music(@"Music\ajapa\さとりんステップ.mp3");
		public static Music さとり行進曲 = new Music(@"Music\ajapa\さとり行進曲.mp3");
		public static Music チルノの日常 = new Music(@"Music\ajapa\チルノの日常.mp3");
		public static Music ハッスル恋娘 = new Music(@"Music\ajapa\ハッスル恋娘.mp3");
		public static Music ピコピコスパーク = new Music(@"Music\ajapa\ピコピコスパーク.mp3");
		public static Music フラン荒野に出る = new Music(@"Music\ajapa\フラン、荒野に出る.mp3");
		public static Music フランのお菓子 = new Music(@"Music\ajapa\フランのお菓子.mp3");
		public static Music モラヴィアワルツ = new Music(@"Music\ajapa\モラヴィアワルツ.mp3");
		public static Music ラクダと旅する = new Music(@"Music\ajapa\ラクダと旅する.mp3");
		public static Music 闇ノミゾ知ル世界 = new Music(@"Music\ajapa\闇ノミゾ知ル世界.mp3");
		public static Music 一人の大演奏 = new Music(@"Music\ajapa\一人の大演奏.mp3");
		public static Music 宇宙トラベル = new Music(@"Music\ajapa\宇宙トラベル.mp3");
		public static Music 縁側から眺める海と舞踊 = new Music(@"Music\ajapa\縁側から眺める海と舞踊.mp3");
		public static Music 王女へ捧げる音楽 = new Music(@"Music\ajapa\王女へ捧げる音楽.mp3");
		public static Music 河童未知の旅 = new Music(@"Music\ajapa\河童、未知の旅.mp3");
		public static Music 壊れた羅針盤 = new Music(@"Music\ajapa\壊れた羅針盤.mp3");
		public static Music 皆既月食と日本酒 = new Music(@"Music\ajapa\皆既月食と日本酒.mp3");
		public static Music 椛の日常 = new Music(@"Music\ajapa\椛の日常.mp3");
		public static Music 吸血鬼の夏 = new Music(@"Music\ajapa\吸血鬼の夏.mp3");
		public static Music 吸血鬼の祈り = new Music(@"Music\ajapa\吸血鬼の祈り.mp3");
		public static Music 銀月の前に = new Music(@"Music\ajapa\銀月の前に.mp3");
		public static Music 月食満ちるまで = new Music(@"Music\ajapa\月食、満ちるまで.mp3");
		public static Music 幻想郷の初秋 = new Music(@"Music\ajapa\幻想郷の初秋.mp3");
		public static Music 幻想郷物語 = new Music(@"Music\ajapa\幻想郷物語.mp3");
		public static Music 向日葵7sCoffee = new Music(@"Music\ajapa\向日葵7s Coffee.mp3");
		public static Music 紅茶を飲みましょう = new Music(@"Music\ajapa\紅茶を飲みましょう.mp3");
		public static Music 裁判長の非非日常 = new Music(@"Music\ajapa\裁判長の非・非日常.mp3");
		public static Music 三日月の宴 = new Music(@"Music\ajapa\三日月の宴.mp3");
		public static Music 残酷なまでに = new Music(@"Music\ajapa\残酷なまでに.mp3");
		public static Music 四季終の時 = new Music(@"Music\ajapa\四季、終の時.mp3");
		public static Music 秋の宵木の葉の傍で = new Music(@"Music\ajapa\秋の宵木の葉の傍で.mp3");
		public static Music 終夏のハロウィン = new Music(@"Music\ajapa\終夏のハロウィン.mp3");
		public static Music 終秋のクリスマス = new Music(@"Music\ajapa\終秋のクリスマス.mp3");
		public static Music 春の桜嵐 = new Music(@"Music\ajapa\春の桜嵐.mp3");
		public static Music 初夏花開く = new Music(@"Music\ajapa\初夏、花開く.mp3");
		public static Music 宵月のうたかるた = new Music(@"Music\ajapa\宵月のうたかるた.mp3");
		public static Music 小人族の大冒険 = new Music(@"Music\ajapa\小人族の大冒険.mp3");
		public static Music 少女哀悼の踊り = new Music(@"Music\ajapa\少女、哀悼の踊り.mp3");
		public static Music 少女奇想天外曲 = new Music(@"Music\ajapa\少女奇想天外曲.mp3");
		public static Music 少年時の旅 = new Music(@"Music\ajapa\少年、時の旅.mp3");
		public static Music 信仰とバベルの塔 = new Music(@"Music\ajapa\信仰とバベルの塔.mp3");
		public static Music 信仰の為の大戦争 = new Music(@"Music\ajapa\信仰の為の大戦争.mp3");
		public static Music 神戦場 = new Music(@"Music\ajapa\神戦場.mp3");
		public static Music 神秘の幻想郷 = new Music(@"Music\ajapa\神秘の幻想郷.mp3");
		public static Music 人形師による演奏 = new Music(@"Music\ajapa\人形師による演奏.mp3");
		public static Music 雪と花 = new Music(@"Music\ajapa\雪と花.mp3");
		public static Music 川辺でお休み = new Music(@"Music\ajapa\川辺でお休み.mp3");
		public static Music 太陽信仰狂信者 = new Music(@"Music\ajapa\太陽信仰狂信者.mp3");
		public static Music 大魔王魔理沙様 = new Music(@"Music\ajapa\大魔王、魔理沙様.mp3");
		public static Music 地の天の川 = new Music(@"Music\ajapa\地の天の川.mp3");
		public static Music 中東巡り巡って = new Music(@"Music\ajapa\中東巡り巡って.mp3");
		public static Music 天を貫く緋想の剣 = new Music(@"Music\ajapa\天を貫く緋想の剣.mp3");
		public static Music 天衣緋想月 = new Music(@"Music\ajapa\天衣緋想月.mp3");
		public static Music 天空の休息所 = new Music(@"Music\ajapa\天空の休息所.mp3");
		public static Music 天神の舞踏会 = new Music(@"Music\ajapa\天神の舞踏会.mp3");
		public static Music 吐零の都 = new Music(@"Music\ajapa\吐零の都.mp3");
		public static Music 冬とこれから = new Music(@"Music\ajapa\冬とこれから.mp3");
		public static Music 冬の森林にて = new Music(@"Music\ajapa\冬の森林にて.mp3");
		public static Music 日照雨 = new Music(@"Music\ajapa\日照雨.mp3");
		public static Music 破滅ジオスパーク = new Music(@"Music\ajapa\破滅ジオスパーク.mp3");
		public static Music 破滅スパーク = new Music(@"Music\ajapa\破滅スパーク.mp3");
		public static Music 破滅スパークエクセリオン = new Music(@"Music\ajapa\破滅スパークエクセリオン.mp3");
		public static Music 白い雪都 = new Music(@"Music\ajapa\白い雪都.mp3");
		public static Music 不安と安らぎの貧困街 = new Music(@"Music\ajapa\不安と安らぎの貧困街.mp3");
		public static Music 風吹く教会 = new Music(@"Music\ajapa\風吹く教会.mp3");
		public static Music 風嵐神 = new Music(@"Music\ajapa\風嵐神.mp3");
		public static Music 風嵐神_改 = new Music(@"Music\ajapa\風嵐神_改.mp3");
		public static Music 法の森のカフェ = new Music(@"Music\ajapa\法の森のカフェ.mp3");
		public static Music 魔宮神殿 = new Music(@"Music\ajapa\魔宮神殿.mp3");
		public static Music 満月夜風にあたり = new Music(@"Music\ajapa\満月、夜風にあたり.mp3");
		public static Music 満月夜風にあたりピアノ = new Music(@"Music\ajapa\満月、夜風にあたりピアノ.mp3");
		public static Music 無数の積み石 = new Music(@"Music\ajapa\無数の積み石.mp3");
		public static Music 夜の野原 = new Music(@"Music\ajapa\夜の野原.mp3");
		public static Music 妖精の悪どいステップ = new Music(@"Music\ajapa\妖精の悪どいステップ.mp3");
		public static Music 落ちるが滝 = new Music(@"Music\ajapa\落ちるが滝.mp3");
		public static Music 流れる椛の如く = new Music(@"Music\ajapa\流れる椛の如く.mp3");
		public static Music 緑豊かな幻想郷 = new Music(@"Music\ajapa\緑豊かな幻想郷.mp3");
		public static Music 恋色ジャズタイム = new Music(@"Music\ajapa\恋色ジャズタイム.mp3");
		public static Music 恋色魔StarSpace = new Music(@"Music\ajapa\恋色魔Star Space.mp3");
		public static Music 煉獄への扉月の表側 = new Music(@"Music\ajapa\煉獄への扉～月の表側.mp3");
		public static Music 煉獄への扉月の裏側 = new Music(@"Music\ajapa\煉獄への扉～月の裏側.mp3");
		public static Music 曖昧な生き = new Music(@"Music\ajapa\曖昧な生き.mp3");
	}
}
